%% Synthetic recovery test for anisotropic IMR model-to-data optimization
clear
clc
close all

[scriptDir, projectDir] = locateProjectPaths();
addpath(fullfile(scriptDir, 'src', 'common'));
addpath(fullfile(scriptDir, 'src', 'forward_solver'));
addpath(fullfile(scriptDir, 'src', 'characterization'));

%% User settings
dataFile = fullfile(projectDir, 'data', 'SicongJinChicken', ...
    'chicken_Rt_data', 'processed_11.mat');

% These settings mirror s_optimize_model_to_data by default. The initial
% conditions are extracted from processed_11, then the target data are
% generated by the forward model with trueParams.
maxmode = 12;
polyOrder = 3;
windowPts = 21;
icVelocityWindowPts = 15;  % forward polynomial derivative window from Rmax
icVelocityPolyOrder = 3;
opt.fit.NumPerturbationModes = 5;

trueParams = struct();
trueParams.G = 5e3;
trueParams.alph = 1;
trueParams.mu = 0.3;
trueParams.ani = [2, 1];

% Loss priority weights after per-trace normalization. Radial receives
% RadialWeight, and mode n receives
% ModeBaseWeight*(ModeReference/(n + ModeWeightOffset))^ModeWeightPower.
opt.loss.RadialWeight = 1.5;
opt.loss.ModeBaseWeight = 1;
opt.loss.ModeReference = 2;
opt.loss.ModeWeightPower = 2;
opt.loss.ModeWeightOffset = 0;

% Parameter bounds. G and mu are optimized in log10-space by default.
opt.bounds.G = [1e3, 5e4];
opt.bounds.alph = [0, 5];
opt.bounds.mu = [5e-3, 5e-1];
opt.bounds.ani = [0, 5; ...
                 0, 5];

% Leave all entries as NaN for this recovery test so the optimizer must
% recover every synthetic material parameter.
opt.fixed.G = NaN;
opt.fixed.alph = NaN;
opt.fixed.mu = NaN;
opt.fixed.ani = [NaN, NaN];

opt.logScale.G = true;
opt.logScale.alph = false;
opt.logScale.mu = true;
opt.logScale.ani = [false, false];

% Forward-solver controls.
opt.sim.tsteps = 3000;          % fallback only; optimizer feeds target times
opt.sim.RelTol = 1e-4;
opt.sim.AbsTol = 1e-5;
opt.sim.Nt = 75;
opt.sim.Method = 23;
opt.sim.MaxWallTime = 60;       % seconds per simulation
opt.sim.UseHardTimeout = false;
opt.sim.TimeoutPollInterval = 1;
opt.sim.FailurePenalty = 1e5;
opt.sim.UseLogLoss = true;
opt.sim.LogLossFloor = 1e-12;
opt.sim.TimeMatchTolerance = 1e-8;
opt.sim.VerifyTimeExtraction = true;
opt.sim.PrintFailures = true;
opt.sim.PrintSuccess = false;

% Bayes-opt controls. Increase these for a more exhaustive recovery test.
opt.bayes.MaxObjectiveEvaluations = 80;
opt.bayes.NumSeedPoints = 16;
opt.bayes.UseLatinHypercubeInitialX = true;
opt.bayes.InitialRegionFraction = 1; % full optimizer bound range
opt.bayes.UseParallel = true;
opt.bayes.NumWorkers = [];
opt.bayes.ParallelPoolProfile = '';
opt.bayes.RestartParallelPool = false;
opt.bayes.MinWorkerUtilization = [];
opt.bayes.ParallelMethod = 'clipped-model-prediction';
opt.bayes.IsObjectiveDeterministic = true;
opt.bayes.AcquisitionFunctionName = 'lower-confidence-bound';
opt.bayes.ExplorationRatio = 0.75;
opt.bayes.Verbose = 1;
opt.bayes.PlotFcn = {};

% Optional local refinement from the best Bayes-opt points. This is enabled
% here because the synthetic, noiseless target should admit a very low loss.
opt.refine.Enabled = true;
opt.refine.NumStarts = 3;
opt.refine.Display = 'iter-detailed';
opt.refine.UseParallel = false;
opt.refine.MaxFunctionEvaluations = 50;
opt.refine.MaxIterations = 10;
opt.refine.OptimalityTolerance = 1e-10;
opt.refine.FunctionTolerance = 1e-10;
opt.refine.StepTolerance = 1e-10;
opt.refine.FiniteDifferenceType = 'forward';
opt.refine.Algorithm = 'interior-point';

opt.randomSeed = 11;
opt.outputFile = fullfile(scriptDir, ...
    'synthetic_model_to_data_recovery.mat');
opt.makePlot = true;

%% Load processed_11 and extract initial conditions
if ~isempty(opt.randomSeed)
    rng(opt.randomSeed, 'twister');
end

if ~isfile(dataFile)
    error('Could not find the data file: %s', dataFile);
end
load(dataFile)

pxpermicron = 3.2;

expR = amp_extract_fft(1, :) .* 1e-6 .* pxpermicron;
texp = (0:numel(expR)-1) .* 1e-6;

amps_og = amp_extract_fft(3:end, :) ./ expR .* 1e-6 .* pxpermicron;
Req = expR(end);

maxmode = min(maxmode, size(amps_og, 1) + 1);
windowPts = min(windowPts, 2 * floor((size(amps_og, 2) - 1) / 2) + 1);
if mod(windowPts, 2) == 0
    windowPts = windowPts - 1;
end

amps = sgolayfilt(amps_og(1:maxmode-1, :), polyOrder, windowPts, [], 2);

[Rmax, maxidx] = max(expR);
tc = Rmax * sqrt(1000 / 101325);

epnm0 = amps(:, maxidx);
epnmd0 = computeInitialModeVelocities(amps, texp, maxidx, tc, ...
    icVelocityWindowPts, icVelocityPolyOrder);
eqWindow = max(1, size(amps, 2)-20):size(amps, 2);
epnmeq = mean(amps(:, eqWindow), 2);

fitIdx = maxidx:numel(texp);
tfit_nd = (texp(fitIdx) - texp(maxidx)) ./ tc;
tf_nd = max(tfit_nd);

modeRows = 3:maxmode+1;
n = mode_extract_fft(modeRows, 1);
n = n(:).';
m = zeros(size(n));

%% Generate synthetic target data
fprintf('Generating synthetic target data from processed_11 initial conditions.\n');
fprintf('True parameters: G=%.6g Pa, alph=%.6g, mu=%.6g Pa*s, ani=[%.6g %.6g]\n', ...
    trueParams.G, trueParams.alph, trueParams.mu, trueParams.ani(1), ...
    trueParams.ani(2));

[tSynthetic, R_data, ep_data] = f_call_IMRv2_exp(Rmax, Req, epnm0, ...
    epnmd0, epnmeq, n, m, trueParams.mu, trueParams.G, ...
    trueParams.alph, trueParams.ani, 0.056, -0 * 101325, 50e3, ...
    tf_nd, numel(tfit_nd), false, ...
    'RelTol', opt.sim.RelTol, ...
    'AbsTol', opt.sim.AbsTol, ...
    'Nt', opt.sim.Nt, ...
    'Method', opt.sim.Method, ...
    'MaxWallTime', opt.sim.MaxWallTime, ...
    'OutputTimeNd', tfit_nd);

tSynthetic = tSynthetic(:);
R_data = R_data(:);
if numel(tSynthetic) ~= numel(tfit_nd)
    error('Synthetic solve returned %d times, expected %d.', ...
        numel(tSynthetic), numel(tfit_nd));
end
syntheticTimeMismatch = max(abs(tSynthetic - tfit_nd(:)));
if syntheticTimeMismatch > opt.sim.TimeMatchTolerance
    error('Synthetic solve did not return the requested time grid. Max |dt*| = %.3g.', ...
        syntheticTimeMismatch);
end

firstCollapseIdx = findFirstCollapseIndex(R_data);
epFitIdx = 1:firstCollapseIdx;
firstCollapseTimeNd = tfit_nd(firstCollapseIdx);

nmodes = size(ep_data, 2);
modeEnergy = sum(ep_data(epFitIdx, :).^2, 1);
[~, modeEnergyOrder] = sort(modeEnergy, 'descend');
nFitModes = min(opt.fit.NumPerturbationModes, nmodes);
fitModeIdx = sort(modeEnergyOrder(1:nFitModes));
testModeIdx = setdiff(1:nmodes, fitModeIdx, 'stable');

lossWeights = makePriorityLossWeights(n, opt.loss);
aR = lossWeights.radial / norm(R_data);
sEP = vecnorm(ep_data(epFitIdx, :), 2, 1);
sEP(sEP < eps) = 1;
aEP = lossWeights.modes ./ sEP;
yData = [aR .* R_data; reshape(ep_data(epFitIdx, fitModeIdx) .* ...
    aEP(fitModeIdx), [], 1)];

xDataAll = struct( ...
    'Rmax', Rmax, ...
    'Req', Req, ...
    'epnm0', epnm0, ...
    'epnmd0', epnmd0, ...
    'epnmeq', epnmeq, ...
    'n', n, ...
    'm', m, ...
    'sig', 0.056, ...
    'p_a', -0 * 101325, ...
    'f_a', 50e3, ...
    'rho', 1000, ...
    'p8', 101325, ...
    'tf_nd', tf_nd, ...
    'tfit_nd', tfit_nd(:), ...
    'R_data', R_data, ...
    'ep_data', ep_data, ...
    'epFitIdx', epFitIdx, ...
    'firstCollapseIdx', firstCollapseIdx, ...
    'firstCollapseTimeNd', firstCollapseTimeNd, ...
    'fitModeIdx', fitModeIdx, ...
    'testModeIdx', testModeIdx, ...
    'modeEnergy', modeEnergy, ...
    'lossWeights', lossWeights, ...
    'aR', aR, ...
    'aEP', aEP, ...
    'y_data', yData, ...
    'syntheticTrueParams', trueParams, ...
    'syntheticTimeMismatch', syntheticTimeMismatch, ...
    'ultra', false);

xDataOpt = xDataAll;
xData = xDataAll;  % saved alias for compatibility with older analysis code

%% Build and verify the optimization problem
paramSpec = buildParameterSpec(opt);
bayesoptVars = buildBayesoptVariables(paramSpec);
[lbOpt, ubOpt] = optimizerBounds(paramSpec);
trueZ = paramsToOptimizerVector(trueParams, paramSpec);

[trueY, trueRunInfo, trueSim] = f_optimize_model_to_data_predict(trueZ, ...
    xDataOpt, paramSpec, opt.sim);
trueRawLoss = normalizedVectorLoss(yData, trueY);
trueObjective = objectiveFromRawLoss(trueRawLoss, opt.sim);

if ~isempty(bayesoptVars)
    opt.bayes = prepareBayesoptParallelPool(opt.bayes);
end
if opt.bayes.UseLatinHypercubeInitialX
    opt.bayes.InitialX = makeLowerRegionLatinHypercubeInitialX( ...
        paramSpec, opt.bayes.NumSeedPoints, opt.bayes.InitialRegionFraction);
end

fprintf('Training perturbation modes: %s\n', num2str(n(fitModeIdx)));
fprintf('Held-out perturbation modes: %s\n', num2str(n(testModeIdx)));
printLossWeights(n, fitModeIdx, lossWeights);
printParameterSpec(paramSpec);
fprintf(['First synthetic collapse at post-Rmax sample %d/%d: ', ...
    't* = %.6g, R/Rmax = %.6g\n'], firstCollapseIdx, numel(tfit_nd), ...
    firstCollapseTimeNd, R_data(firstCollapseIdx));
fprintf('Synthetic time-grid mismatch = %.3g\n', syntheticTimeMismatch);
fprintf('Loss at true synthetic parameters: raw=%.6g, objective=%.6g\n', ...
    trueRawLoss, trueObjective);
fprintf('True-parameter simulation success = %d (%s)\n', ...
    trueRunInfo.success, trueRunInfo.message);
if isfield(opt.bayes, 'InitialX') && ~isempty(opt.bayes.InitialX)
    disp('Bayes-opt initial Latin-hypercube points:')
    disp(opt.bayes.InitialX)
end

%% Bayesian optimization
lossfun = @(T) f_optimize_model_to_data_loss(T, xDataOpt, paramSpec, ...
    opt.sim);

if isempty(bayesoptVars)
    results = [];
    bestZFromBayes = [];
    fvalFromBayes = lossfun([]);
else
    bayesArgs = makeBayesoptArgs(opt.bayes);
    results = bayesopt(lossfun, bayesoptVars, bayesArgs{:});
    bestZFromBayes = tableToOptimizerMatrix(results.XAtMinObjective, ...
        paramSpec);
    fvalFromBayes = results.MinObjective;
end

%% Optional local refinement
refineOutput = [];
solutions = [];
if opt.refine.Enabled && ~isempty(bayesoptVars)
    starts = bestBayesStarts(results, paramSpec, opt.refine.NumStarts);
    customStarts = CustomStartPointSet(starts);
    lsqopts = makeLsqOptions(opt.refine);
    objfun = @(z, xDataIn) f_optimize_model_to_data_predict( ...
        z, xDataIn, paramSpec, opt.sim);

    problem = createOptimProblem('lsqcurvefit', ...
        'x0', starts(1, :), ...
        'objective', objfun, ...
        'xdata', xDataOpt, ...
        'ydata', yData, ...
        'lb', lbOpt, ...
        'ub', ubOpt, ...
        'options', lsqopts);

    ms = MultiStart('UseParallel', opt.refine.UseParallel, ...
        'StartPointsToRun', 'all');
    [bestZ, fval, exitflag, refineOutput, solutions] = run(ms, problem, ...
        customStarts);
else
    bestZ = bestZFromBayes;
    fval = fvalFromBayes;
    exitflag = NaN;
end

%% Evaluate and report recovery
bestParams = f_unpack_model_to_data_params(bestZ, paramSpec);
[bestY, bestRunInfo, bestSim] = f_optimize_model_to_data_predict(bestZ, ...
    xDataOpt, paramSpec, opt.sim);
bestRawLoss = normalizedVectorLoss(yData, bestY);
bestObjective = objectiveFromRawLoss(bestRawLoss, opt.sim);

trainModeLoss = computePerturbationSubsetLoss(bestSim, xDataAll, ...
    xDataAll.fitModeIdx);
heldoutModeLoss = computePerturbationSubsetLoss(bestSim, xDataAll, ...
    xDataAll.testModeIdx);
allModeLoss = computePerturbationSubsetLoss(bestSim, xDataAll, 1:nmodes);
timeVerification = makeTimeExtractionVerification(bestSim, xDataAll, ...
    bestRunInfo);
recoveryTable = makeRecoveryTable(trueParams, bestParams);

fprintf('\nSynthetic recovery result\n');
fprintf('  G     = %.6g Pa (true %.6g)\n', bestParams.G, trueParams.G);
fprintf('  alph  = %.6g (true %.6g)\n', bestParams.alph, trueParams.alph);
fprintf('  mu    = %.6g Pa*s (true %.6g)\n', bestParams.mu, trueParams.mu);
fprintf('  ani   = [%.6g %.6g] (true [%.6g %.6g])\n', ...
    bestParams.ani(1), bestParams.ani(2), trueParams.ani(1), ...
    trueParams.ani(2));
fprintf('  raw loss       = %.6g\n', bestRawLoss);
fprintf('  objective loss = %.6g\n', bestObjective);
fprintf('  true raw loss  = %.6g\n', trueRawLoss);
fprintf('  train mode loss   = %.6g\n', trainModeLoss);
fprintf('  held-out mode loss = %.6g\n', heldoutModeLoss);
fprintf('  all mode loss     = %.6g\n', allModeLoss);
fprintf('  max requested/returned simulation time mismatch = %.3g\n', ...
    bestRunInfo.maxRequestedReturnedTimeMismatch);
fprintf('  max radial time extraction mismatch = %.3g\n', ...
    timeVerification.maxRadialAbsDt);
fprintf('  max perturbation time extraction mismatch = %.3g\n', ...
    timeVerification.maxPerturbationAbsDt);
disp(recoveryTable)

if opt.makePlot
    plotSyntheticRecoveryFit(bestSim, trueSim, xDataAll, bestParams, ...
        trueParams);
end

save(opt.outputFile, 'opt', 'paramSpec', 'xData', 'xDataAll', ...
    'xDataOpt', 'results', 'trueParams', 'trueZ', 'trueRawLoss', ...
    'trueObjective', 'trueRunInfo', 'trueSim', 'bestZ', 'bestParams', ...
    'bestRawLoss', 'bestObjective', 'bestRunInfo', 'bestSim', ...
    'recoveryTable', 'timeVerification', 'trainModeLoss', ...
    'heldoutModeLoss', 'allModeLoss', 'fval', 'exitflag', ...
    'refineOutput', 'solutions');

%% Local helper functions
function [scriptDir, projectDir] = locateProjectPaths()
    candidates = {};
    candidates = addCandidate(candidates, fileparts(mfilename('fullpath')));
    candidates = addCandidate(candidates, ...
        fileparts(which('s_synthetic_model_to_data_recovery')));
    candidates = addCandidate(candidates, fileparts(which('f_call_IMRv2_exp')));
    candidates = addCandidate(candidates, pwd);
    candidates = addCandidate(candidates, fullfile(pwd, 'IMRv2'));
    candidates = addCandidate(candidates, fileparts(pwd));
    candidates = addCandidate(candidates, fullfile(fileparts(pwd), 'IMRv2'));

    for ii = 1:numel(candidates)
        candidate = candidates{ii};
        if isImrScriptDir(candidate)
            thisProjectDir = fileparts(candidate);
            if isfolder(fullfile(thisProjectDir, 'data'))
                scriptDir = candidate;
                projectDir = thisProjectDir;
                return
            end
        end
    end

    for ii = 1:numel(candidates)
        candidate = candidates{ii};
        if isfolder(fullfile(candidate, 'IMRv2')) && ...
                isImrScriptDir(fullfile(candidate, 'IMRv2')) && ...
                isfolder(fullfile(candidate, 'data'))
            scriptDir = fullfile(candidate, 'IMRv2');
            projectDir = candidate;
            return
        end
    end

    error(['Could not locate the Anisotropic_material_IMR project root. ', ...
        'Run this script from the project root or the IMRv2 folder.']);
end

function candidates = addCandidate(candidates, candidate)
    if isempty(candidate) || ~ischar(candidate)
        return
    end
    candidate = char(candidate);
    if isempty(candidate) || ~isfolder(candidate)
        return
    end
    candidate = char(strrep(candidate, '/', filesep));
    if ~any(strcmpi(candidates, candidate))
        candidates{end+1} = candidate;
    end
end

function tf = isImrScriptDir(candidate)
    tf = ~isempty(candidate) && isfolder(candidate) && ...
        isfile(fullfile(candidate, 'f_call_IMRv2_exp.m')) && ...
        isfolder(fullfile(candidate, 'src', 'forward_solver'));
end

function epnmd0 = computeInitialModeVelocities(amps, texp, maxidx, tc, ...
    windowPts, polyOrder)
    epnmd0 = zeros(size(amps, 1), 1);
    if nargin < 5 || isempty(windowPts)
        windowPts = 15;
    end
    if nargin < 6 || isempty(polyOrder)
        polyOrder = 3;
    end

    windowIdx = localForwardWindow(size(amps, 2), maxidx, windowPts);
    tstar = (texp(windowIdx) - texp(maxidx)) ./ tc;
    fitOrder = min(polyOrder, numel(windowIdx) - 1);
    if fitOrder < 1
        return
    end

    for ii = 1:size(amps, 1)
        p = polyfit(tstar(:), amps(ii, windowIdx).', fitOrder);
        epnmd0(ii) = polyval(polyder(p), 0);
    end
end

function windowIdx = localForwardWindow(nSamples, startIdx, windowPts)
    windowPts = max(3, round(windowPts));
    if mod(windowPts, 2) == 0
        windowPts = windowPts - 1;
    end
    windowPts = min(windowPts, nSamples);
    startIdx = min(max(1, startIdx), nSamples);
    lastIdx = min(nSamples, startIdx + windowPts - 1);
    windowIdx = startIdx:lastIdx;
end

function firstCollapseIdx = findFirstCollapseIndex(R_data)
    R_data = R_data(:);
    if numel(R_data) < 3
        firstCollapseIdx = numel(R_data);
        return
    end

    smoothWindow = min(7, 2 * floor((numel(R_data) - 1) / 2) + 1);
    if smoothWindow >= 3
        R_smooth = movmean(R_data, smoothWindow, 'Endpoints', 'shrink');
    else
        R_smooth = R_data;
    end

    dR = diff(R_smooth);
    localMinIdx = find(dR(1:end-1) < 0 & dR(2:end) >= 0) + 1;
    if ~isempty(localMinIdx)
        cumulativeMin = cummin(R_smooth);
        drop = R_smooth(1) - min(R_smooth);
        minDrop = max(1e-6, 0.05 * drop);
        valid = R_smooth(localMinIdx) <= cumulativeMin(localMinIdx) + ...
            1e-6 & R_smooth(localMinIdx) <= R_smooth(1) - minDrop;
        localMinIdx = localMinIdx(valid);
    end

    if isempty(localMinIdx)
        [~, firstCollapseIdx] = min(R_smooth);
    else
        firstCollapseIdx = localMinIdx(1);
    end
end

function paramSpec = buildParameterSpec(opt)
    paramSpec = repmat(struct('name', '', 'variableName', '', ...
        'bounds', [], 'optimizerBounds', [], 'logScale', false, ...
        'optimize', true, 'fixedValue', NaN), 5, 1);

    fixed = fixedParameterValues(opt);
    paramSpec(1) = makeParamSpec('G', opt.bounds.G, opt.logScale.G, ...
        fixed.G);
    paramSpec(2) = makeParamSpec('alph', opt.bounds.alph, ...
        opt.logScale.alph, fixed.alph);
    paramSpec(3) = makeParamSpec('mu', opt.bounds.mu, opt.logScale.mu, ...
        fixed.mu);
    paramSpec(4) = makeParamSpec('ani1', opt.bounds.ani(1, :), ...
        opt.logScale.ani(1), fixed.ani(1));
    paramSpec(5) = makeParamSpec('ani2', opt.bounds.ani(2, :), ...
        opt.logScale.ani(2), fixed.ani(2));
end

function fixed = fixedParameterValues(opt)
    fixed = struct('G', NaN, 'alph', NaN, 'mu', NaN, 'ani', [NaN, NaN]);
    if isfield(opt, 'fixed')
        fixed = copyFixedField(opt.fixed, fixed, 'G');
        fixed = copyFixedField(opt.fixed, fixed, 'alph');
        fixed = copyFixedField(opt.fixed, fixed, 'mu');
        if isfield(opt.fixed, 'ani') && ~isempty(opt.fixed.ani)
            fixed.ani = opt.fixed.ani(:).';
        end
    end
    if numel(fixed.ani) ~= 2
        error('opt.fixed.ani must contain exactly two values.');
    end
end

function fixed = copyFixedField(source, fixed, fieldName)
    if isfield(source, fieldName) && ~isempty(source.(fieldName))
        fixed.(fieldName) = source.(fieldName);
    end
end

function spec = makeParamSpec(name, bounds, logScale, fixedValue)
    if numel(bounds) ~= 2 || bounds(1) > bounds(2)
        error('Bounds for %s must be [lower upper] with lower <= upper.', ...
            name);
    end
    isFixed = isfinite(fixedValue) || bounds(1) == bounds(2);
    if bounds(1) == bounds(2)
        fixedValue = bounds(1);
    end
    if logScale && ~isFixed && any(bounds <= 0)
        error('Log-scaled parameter %s must have strictly positive bounds.', ...
            name);
    end
    spec.name = name;
    spec.bounds = bounds;
    spec.logScale = logScale;
    spec.optimize = ~isFixed;
    spec.fixedValue = fixedValue;
    if logScale
        spec.variableName = ['log10_' name];
        if isFixed
            spec.optimizerBounds = [];
        else
            spec.optimizerBounds = log10(bounds);
        end
    else
        spec.variableName = name;
        if isFixed
            spec.optimizerBounds = [];
        else
            spec.optimizerBounds = bounds;
        end
    end
end

function vars = buildBayesoptVariables(paramSpec)
    vars = [];
    for ii = 1:numel(paramSpec)
        if ~paramSpec(ii).optimize
            continue
        end
        thisVar = optimizableVariable(paramSpec(ii).variableName, ...
            paramSpec(ii).optimizerBounds);
        if isempty(vars)
            vars = thisVar;
        else
            vars(end+1, 1) = thisVar; %#ok<AGROW>
        end
    end
end

function [lbOpt, ubOpt] = optimizerBounds(paramSpec)
    activeSpec = activeParameterSpec(paramSpec);
    lbOpt = zeros(1, numel(activeSpec));
    ubOpt = zeros(1, numel(activeSpec));
    for ii = 1:numel(activeSpec)
        lbOpt(ii) = activeSpec(ii).optimizerBounds(1);
        ubOpt(ii) = activeSpec(ii).optimizerBounds(2);
    end
end

function initialX = makeLowerRegionLatinHypercubeInitialX(paramSpec, ...
    nPoints, regionFraction)
    paramSpec = activeParameterSpec(paramSpec);
    if nPoints < 1 || isempty(paramSpec)
        initialX = table();
        return
    end
    if regionFraction <= 0 || regionFraction > 1
        error('InitialRegionFraction must be in the interval (0, 1].');
    end

    nVars = numel(paramSpec);
    x = zeros(nPoints, nVars);
    for jj = 1:nVars
        lb = paramSpec(jj).optimizerBounds(1);
        ub = paramSpec(jj).optimizerBounds(2);
        upper = lb + regionFraction * (ub - lb);
        strata = ((0:nPoints-1)' + rand(nPoints, 1)) ./ nPoints;
        strata = strata(randperm(nPoints));
        x(:, jj) = lb + strata .* (upper - lb);
    end

    initialX = array2table(x, 'VariableNames', ...
        {paramSpec.variableName});
end

function bayesOpts = prepareBayesoptParallelPool(bayesOpts)
    if ~bayesOpts.UseParallel
        return
    end

    p = gcp('nocreate');
    if optionValue(bayesOpts, 'RestartParallelPool', false) && ~isempty(p)
        delete(p);
        p = [];
    end

    if isempty(p)
        try
            p = startRequestedPool(bayesOpts);
        catch ME
            warning('ModelToData:ParallelPoolStartFailed', ...
                ['Could not start a parallel pool for bayesopt: %s\n', ...
                'Continuing with UseParallel=false.'], ME.message);
            bayesOpts.UseParallel = false;
            return
        end
    end

    nWorkers = p.NumWorkers;
    fprintf('Bayes-opt parallel pool: %d workers (%s).\n', ...
        nWorkers, class(p));
    if nWorkers < 2
        warning('Bayesopt has UseParallel=true but the pool has only one worker.');
    end

    if isempty(optionValue(bayesOpts, 'MinWorkerUtilization', []))
        bayesOpts.MinWorkerUtilization = nWorkers;
    elseif bayesOpts.MinWorkerUtilization > nWorkers
        warning(['MinWorkerUtilization (%d) exceeds pool size (%d); ', ...
            'using %d.'], bayesOpts.MinWorkerUtilization, nWorkers, ...
            nWorkers);
        bayesOpts.MinWorkerUtilization = nWorkers;
    end
    fprintf('Bayes-opt MinWorkerUtilization: %d.\n', ...
        bayesOpts.MinWorkerUtilization);

    if bayesOpts.NumSeedPoints < nWorkers
        fprintf(['Increasing NumSeedPoints from %d to %d so the initial ', ...
            'parallel batch can fill the pool.\n'], ...
            bayesOpts.NumSeedPoints, nWorkers);
        bayesOpts.NumSeedPoints = nWorkers;
    end
end

function p = startRequestedPool(bayesOpts)
    profile = optionValue(bayesOpts, 'ParallelPoolProfile', '');
    nWorkers = optionValue(bayesOpts, 'NumWorkers', []);
    if isempty(profile) && isempty(nWorkers)
        p = parpool;
    elseif isempty(profile)
        p = parpool(nWorkers);
    elseif isempty(nWorkers)
        p = parpool(profile);
    else
        p = parpool(profile, nWorkers);
    end
end

function value = optionValue(options, fieldName, defaultValue)
    if isfield(options, fieldName) && ~isempty(options.(fieldName))
        value = options.(fieldName);
    else
        value = defaultValue;
    end
end

function lossWeights = makePriorityLossWeights(n, lossOpts)
    radialWeight = optionValue(lossOpts, 'RadialWeight', 1);
    modeBaseWeight = optionValue(lossOpts, 'ModeBaseWeight', 1);
    modeReference = optionValue(lossOpts, 'ModeReference', 2);
    modePower = optionValue(lossOpts, 'ModeWeightPower', 2);
    modeOffset = optionValue(lossOpts, 'ModeWeightOffset', 0);

    modeDenom = abs(n(:).') + modeOffset;
    if modeReference <= 0 || any(modeDenom <= 0)
        error(['Mode weights require ModeReference and n + ' ...
            'ModeWeightOffset to be positive.']);
    end

    lossWeights = struct();
    lossWeights.radial = radialWeight;
    lossWeights.modes = modeBaseWeight .* ...
        (modeReference ./ modeDenom) .^ modePower;
    lossWeights.modeBaseWeight = modeBaseWeight;
    lossWeights.modeReference = modeReference;
    lossWeights.modePower = modePower;
    lossWeights.modeOffset = modeOffset;
end

function printLossWeights(n, fitModeIdx, lossWeights)
    fprintf(['Loss priority weights: radial=%.6g, mode formula=' ...
        '%.6g*(%.6g/(n+%.6g))^%.6g\n'], lossWeights.radial, ...
        lossWeights.modeBaseWeight, lossWeights.modeReference, ...
        lossWeights.modeOffset, lossWeights.modePower);
    fprintf('Training mode priority weights:\n');
    for ii = 1:numel(fitModeIdx)
        idx = fitModeIdx(ii);
        fprintf('  n=%g: %.6g\n', n(idx), lossWeights.modes(idx));
    end
end

function args = makeBayesoptArgs(bayesOpts)
    args = { ...
        'MaxObjectiveEvaluations', bayesOpts.MaxObjectiveEvaluations, ...
        'UseParallel', bayesOpts.UseParallel, ...
        'IsObjectiveDeterministic', bayesOpts.IsObjectiveDeterministic, ...
        'AcquisitionFunctionName', bayesOpts.AcquisitionFunctionName, ...
        'NumSeedPoints', bayesOpts.NumSeedPoints, ...
        'ExplorationRatio', bayesOpts.ExplorationRatio, ...
        'Verbose', bayesOpts.Verbose};
    if bayesOpts.UseParallel && isfield(bayesOpts, 'MinWorkerUtilization') ...
            && ~isempty(bayesOpts.MinWorkerUtilization)
        args = [args, {'MinWorkerUtilization', ...
            bayesOpts.MinWorkerUtilization}];
    end
    if bayesOpts.UseParallel && isfield(bayesOpts, 'ParallelMethod') && ...
            ~isempty(bayesOpts.ParallelMethod)
        args = [args, {'ParallelMethod', bayesOpts.ParallelMethod}];
    end
    if isfield(bayesOpts, 'InitialX') && ~isempty(bayesOpts.InitialX)
        args = [args, {'InitialX', bayesOpts.InitialX}];
    end
    if ~isempty(bayesOpts.PlotFcn)
        args = [args, {'PlotFcn', bayesOpts.PlotFcn}];
    end
end

function lsqopts = makeLsqOptions(refineOpts)
    lsqopts = optimoptions('lsqcurvefit', ...
        'Display', refineOpts.Display, ...
        'OptimalityTolerance', refineOpts.OptimalityTolerance, ...
        'FunctionTolerance', refineOpts.FunctionTolerance, ...
        'StepTolerance', refineOpts.StepTolerance, ...
        'MaxFunctionEvaluations', refineOpts.MaxFunctionEvaluations, ...
        'MaxIterations', refineOpts.MaxIterations, ...
        'UseParallel', refineOpts.UseParallel, ...
        'FiniteDifferenceType', refineOpts.FiniteDifferenceType, ...
        'Algorithm', refineOpts.Algorithm);
end

function starts = bestBayesStarts(results, paramSpec, nStarts)
    objectiveTrace = results.ObjectiveTrace;
    xTrace = tableToOptimizerMatrix(results.XTrace, paramSpec);
    [~, order] = sort(objectiveTrace, 'ascend');
    nKeep = min(nStarts, numel(order));
    starts = xTrace(order(1:nKeep), :);
end

function mat = tableToOptimizerMatrix(T, paramSpec)
    activeSpec = activeParameterSpec(paramSpec);
    mat = zeros(height(T), numel(activeSpec));
    for ii = 1:numel(activeSpec)
        mat(:, ii) = T.(activeSpec(ii).variableName);
    end
end

function activeSpec = activeParameterSpec(paramSpec)
    activeSpec = paramSpec([paramSpec.optimize]);
end

function z = paramsToOptimizerVector(params, paramSpec)
    activeSpec = activeParameterSpec(paramSpec);
    z = zeros(1, numel(activeSpec));
    for ii = 1:numel(activeSpec)
        value = physicalParamValue(params, activeSpec(ii).name);
        if activeSpec(ii).logScale
            value = log10(value);
        end
        z(ii) = value;
    end
end

function value = physicalParamValue(params, name)
    switch name
        case 'G'
            value = params.G;
        case 'alph'
            value = params.alph;
        case 'mu'
            value = params.mu;
        case 'ani1'
            value = params.ani(1);
        case 'ani2'
            value = params.ani(2);
        otherwise
            error('Unknown parameter "%s".', name);
    end
end

function printParameterSpec(paramSpec)
    fprintf('Optimized parameters: ');
    activeSpec = activeParameterSpec(paramSpec);
    if isempty(activeSpec)
        fprintf('(none; evaluating fixed parameter set only)\n');
    else
        fprintf('%s\n', strjoin({activeSpec.name}, ', '));
    end

    fixedSpec = paramSpec(~[paramSpec.optimize]);
    if isempty(fixedSpec)
        fprintf('Fixed parameters: (none)\n');
        return
    end
    fixedText = cell(1, numel(fixedSpec));
    for ii = 1:numel(fixedSpec)
        fixedText{ii} = sprintf('%s=%.6g', fixedSpec(ii).name, ...
            fixedSpec(ii).fixedValue);
    end
    fprintf('Fixed parameters: %s\n', strjoin(fixedText, ', '));
end

function loss = normalizedVectorLoss(yData, yModel)
    loss = sqrt(sum((yData - yModel).^2)) / norm(yData);
end

function objective = objectiveFromRawLoss(rawLoss, simOpts)
    if optionValue(simOpts, 'UseLogLoss', false)
        floorValue = optionValue(simOpts, 'LogLossFloor', 1e-12);
        objective = log10(max(rawLoss, floorValue));
    else
        objective = rawLoss;
    end
end

function loss = computePerturbationSubsetLoss(sim, xData, modeIdx)
    if isempty(modeIdx)
        loss = NaN;
        return
    end
    if ~isfield(sim, 'success') || ~sim.success
        loss = NaN;
        return
    end

    epRows = perturbationFitRows(xData);
    if numel(sim.t) ~= numel(xData.tfit_nd)
        loss = NaN;
        return
    end

    timeTol = 1e-8;
    if max(abs(sim.t(:) - xData.tfit_nd(:))) > timeTol
        loss = NaN;
        return
    end

    epModel = sim.epnm(epRows, modeIdx);
    epData = xData.ep_data(epRows, modeIdx);
    weights = xData.aEP(modeIdx);

    if any(~isfinite(epModel(:)))
        loss = NaN;
        return
    end

    weightedData = epData .* weights;
    weightedModel = epModel .* weights;
    denom = norm(weightedData(:));
    if denom < eps
        loss = NaN;
    else
        loss = sqrt(sum((weightedData(:) - weightedModel(:)).^2)) / denom;
    end
end

function epRows = perturbationFitRows(xData)
    if isfield(xData, 'epFitIdx') && ~isempty(xData.epFitIdx)
        epRows = xData.epFitIdx(:);
    else
        epRows = (1:numel(xData.tfit_nd)).';
    end
end

function verification = makeTimeExtractionVerification(sim, xData, runInfo)
    epRows = perturbationFitRows(xData);
    radialRequested = xData.tfit_nd(:);
    perturbationRequested = xData.tfit_nd(epRows);

    if isfield(sim, 't')
        returnedTimes = sim.t(:);
    else
        returnedTimes = [];
    end

    [radialReturned, radialAbsDt] = nearestReturnedTimes(returnedTimes, ...
        radialRequested);
    [perturbationReturned, perturbationAbsDt] = nearestReturnedTimes( ...
        returnedTimes, perturbationRequested);

    verification = struct();
    verification.radialTable = table(radialRequested, radialReturned, ...
        radialAbsDt, 'VariableNames', {'requestedTimeNd', ...
        'nearestReturnedTimeNd', 'absDtNd'});
    verification.perturbationTable = table(epRows, perturbationRequested, ...
        perturbationReturned, perturbationAbsDt, 'VariableNames', ...
        {'rowIndex', 'requestedTimeNd', 'nearestReturnedTimeNd', ...
        'absDtNd'});
    verification.maxRadialAbsDt = maxFinite(radialAbsDt);
    verification.maxPerturbationAbsDt = maxFinite(perturbationAbsDt);
    verification.firstPerturbationRow = epRows(1);
    verification.lastPerturbationRow = epRows(end);
    verification.firstCollapseIdx = xData.firstCollapseIdx;
    verification.firstCollapseTimeNd = xData.firstCollapseTimeNd;
    verification.optimizerPerturbationTimeNd = perturbationRequested;
    verification.runInfo = runInfo;
end

function [nearestTimes, absDt] = nearestReturnedTimes(returnedTimes, ...
    requestedTimes)
    returnedTimes = returnedTimes(:);
    requestedTimes = requestedTimes(:);
    nearestTimes = NaN(size(requestedTimes));
    absDt = NaN(size(requestedTimes));
    if isempty(returnedTimes) || isempty(requestedTimes)
        return
    end

    for ii = 1:numel(requestedTimes)
        [absDt(ii), nearestIdx] = min(abs(returnedTimes - ...
            requestedTimes(ii)));
        nearestTimes(ii) = returnedTimes(nearestIdx);
    end
end

function value = maxFinite(values)
    finiteValues = values(isfinite(values));
    if isempty(finiteValues)
        value = NaN;
    else
        value = max(finiteValues);
    end
end

function recoveryTable = makeRecoveryTable(trueParams, bestParams)
    parameter = {'G'; 'alph'; 'mu'; 'ani1'; 'ani2'};
    trueValue = [trueParams.G; trueParams.alph; trueParams.mu; ...
        trueParams.ani(1); trueParams.ani(2)];
    recoveredValue = [bestParams.G; bestParams.alph; bestParams.mu; ...
        bestParams.ani(1); bestParams.ani(2)];
    absoluteError = recoveredValue - trueValue;
    relativeErrorPct = 100 .* absoluteError ./ max(abs(trueValue), eps);
    recoveryTable = table(parameter, trueValue, recoveredValue, ...
        absoluteError, relativeErrorPct);
end

function plotSyntheticRecoveryFit(bestSim, trueSim, xData, bestParams, ...
    trueParams)
    if ~isfield(bestSim, 'success') || ~bestSim.success
        warning('Best simulation did not complete, so no recovery plot was made.');
        return
    end
    hasTrue = isfield(trueSim, 'success') && trueSim.success;

    figure('Name', 'Synthetic model-to-data recovery')
    plotl = ceil(sqrt(numel(xData.n) + 1));

    subplot(plotl, plotl, 1)
    hold on
    hFit = plot(bestSim.t, bestSim.R, '-', 'LineWidth', 1.5);
    if hasTrue
        hTrue = plot(trueSim.t, trueSim.R, 'k--', 'LineWidth', 1.2);
    else
        hTrue = gobjects(0);
    end
    hData = plot(xData.tfit_nd, xData.R_data, 'o');
    xlabel("t^*")
    ylabel("R")
    title(sprintf(['fit: G=%.3g, \\mu=%.3g, \\alpha=%.3g, ', ...
        'ani=[%.3g %.3g]'], bestParams.G, bestParams.mu, ...
        bestParams.alph, bestParams.ani(1), bestParams.ani(2)))
    if hasTrue
        legend([hFit, hTrue, hData], {'recovered', 'true', ...
            'synthetic data'}, 'Location', 'best')
    else
        legend([hFit, hData], {'recovered', 'synthetic data'}, ...
            'Location', 'best')
    end

    for ii = 1:numel(xData.n)
        subplot(plotl, plotl, ii + 1)
        hold on
        plot(bestSim.t, bestSim.epnm(:, ii), '-', 'LineWidth', 1.5)
        if hasTrue
            plot(trueSim.t, trueSim.epnm(:, ii), 'k--', 'LineWidth', 1.2)
        end
        plot(xData.tfit_nd, xData.ep_data(:, ii), 'r^')
        xlabel("t^*")
        ylabel(sprintf('$\\epsilon_{%.0f}$', xData.n(ii)), ...
            'Interpreter', 'latex')
    end

    sgtitle(sprintf(['Synthetic truth: G=%.3g, \\mu=%.3g, ', ...
        '\\alpha=%.3g, ani=[%.3g %.3g]'], trueParams.G, ...
        trueParams.mu, trueParams.alph, trueParams.ani(1), ...
        trueParams.ani(2)))
end
