name: Format check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  auto-indent:

    name: Code formatting

    runs-on: ubuntu-latest

    continue-on-error: true  # Does not stop other workflows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run Auto Indentation
        uses: matlab-actions/run-command@v1
        with:
          command: | 
            cd('toolchain');
            s_format;

      - name: Check for uncommitted changes
        run: |
          if ! git diff --quiet; then
            echo "Code formatting issues detected. Please run toolchain/s_format.m and commit the changes."
            exit 1
          fi
