name: Neatness Check
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:

    name: Linter for toolchain and src
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Check if MATLAB is Installed
        run: matlab -batch "disp('MATLAB is installed and ready');"

      - name: Run MATLAB Linting
        uses: matlab-actions/command@v2
        with:
          command: |
             cd toolchain;
             lint.m;
